# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'navigation_tutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for navigation_tutorial

  target 'navigation_tutorial-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'navigation_tutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'navigation_tutorial-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for navigation_tutorial-tvOS

  target 'navigation_tutorial-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
